[iOS] Mediapicker
MateeDevs/devstack-native-app pull request #106
Opened 2024-04-29 09:32 UTC by krystofprihoda

# :pencil: Description
- This PR adds a native picker for choosing any type of media from the gallery requested by @Seidak. What can be chosen from the gallery can be set by the filter variable (by default video & images) and the number of items using the selectionLimit var in MediaPickerViewController.
- The usage of this component is demonstrated in the Recipes tab.
- I commented out all the Rocket code since it did not work for me but all of this was done in a single commit that can be dropped before the merge if necessary.

# :bulb: What’s new?
- Media Picker supported from iOS 14+.

https://github.com/user-attachments/assets/7fb190bd-7d0a-4b60-bc8f-f1484dc0c97c

# :no_mouth: What’s missing?
- Rockets. 🤷🏼

2024-05-23 09:33 UTC, tomas-bat requested changes
Did you also try to find some SwiftUI solutions for this problem?

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
> +struct MediaPickerViewController: UIViewControllerRepresentable {
You use this in other packages, so it probably needs to be `public`

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
> +    var itemProviders: [NSItemProvider] = []
What about some encapsulation? Private properties, initializer, ...

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/Recipes/Sources/Recipes/MediaPicker/MediaPickerView.swift
> +            Button("Add Media") {
We use localization in Devstack, too.

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
> +struct MediaPickerViewController: UIViewControllerRepresentable {
Is `ViewController` an appropriate suffix for a SwiftUI view?

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Does this support selecting media multiple times? E. g. if you select some items and then you want to edit that selection..

2024-05-23 09:33 UTC, tomas-bat commented on ios/PresentationLayer/Recipes/Sources/Recipes/RecipesFlowController.swift
> +}
Isn't this a general protocol that can be used in any package? If so, it should be in `UIToolkit` instead.

2024-06-14 09:36 UTC, krystofprihoda commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Yes, this supports multiple items (de)selection – I have added a video of the behavior.

2024-06-14 09:37 UTC, krystofprihoda commented
> Did you also try to find some SwiftUI solutions for this problem?

@tomas-bat
Unfortunately I haven't found any SwiftUI alternatives supported by iOS 15. :(

2024-06-14 10:12 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Yeah, but I mean the ability to edit the selection **after** you've confirmed the selection 😅 In the video that you recorded, if you wanted to edit the selection at the end.

2024-06-17 09:30 UTC, krystofprihoda commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Ah, I see. 😄 No, you are unable edit the selection after you confirm it and the modal is dismissed. It was not part of the task and I can't think of any alternatives or apps that would let you do this.

2024-06-17 13:26 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Well, most apps usually allow you to edit your photo selection. Usually via their own UI, though... 

If we're implementing this into DevStack, we should probably implement it as a representative example, the inability to edit your selection seems like a big limitation.. 

The implementation shouldn't be hard, you just need to remember the asset identifier of the selected images and add these identifiers to `PHPickerController`'s configuration property `preselectedAssetIdentifiers`.

2024-06-17 13:57 UTC, tomas-bat commented
Btw I haven't experienced any issues with Rockets.. 🤔 What doesn't work for you?

2024-09-16 06:48 UTC, krystofprihoda commented
> Btw I haven't experienced any issues with Rockets.. 🤔 What doesn't work for you?

I can't build the project when rockets are part of it... I will drop the commit during the rebase if it works for you.

2024-09-16 06:56 UTC, krystofprihoda commented
🎞️ Updated the preview video.

2024-09-23 11:49 UTC, tomas-bat commented on ios/PresentationLayer/Recipes/Sources/Recipes/Media/MediaView.swift
> +                                        })
I'd prefer a more idiomatic syntax:
```suggestion
                                        Button {
                                            viewModel.onIntent(.removeMedia(by: media.hashValue))
                                        } label: {
                                            Image(systemName: "plus")
                                                .rotationEffect(.degrees(45))
                                                .foregroundColor(.white)
                                                .padding()
                                                .background(
                                                    Capsule()
                                                        .fill(.red)
                                                        .clipped()
                                                        .shadow(color: Color.black.opacity(0.25), radius: 4, x: 0, y: 1)
                                                )
                                                .padding([.top, .trailing])
                                        }
```

2024-09-23 11:49 UTC, tomas-bat commented on ios/PresentationLayer/Recipes/Sources/Recipes/RecipesFlowController.swift
> +}
This is now defined both here and in `MediaPickerView` 🤔 Can it be removed here?

2024-09-23 11:49 UTC, tomas-bat commented on ios/PresentationLayer/UIToolkit/Sources/UIToolkit/BaseViews/UIKit/UIViewController/MediaPickerViewController.swift
Nice ✅

2024-09-23 11:49 UTC, tomas-bat commented
> I can't build the project when rockets are part of it... I will drop the commit during the rebase if it works for you.

Did you run `setup.sh`? 😅

2024-09-27 04:10 UTC, krystofprihoda commented on ios/PresentationLayer/Recipes/Sources/Recipes/Media/MediaView.swift
> +                                        })
Looks cleaner, changed✅

2024-10-07 03:26 UTC, krystofprihoda commented
> > I can't build the project when rockets are part of it... I will drop the commit during the rebase if it works for you.
> 
> Did you run `setup.sh`? 😅

Tried running after rebasing now and works, probably did not run it before or don't know what was the issue.

2024-10-09 07:55 UTC, tomas-bat approved these changes
🎉

2024-10-09 10:05 UTC, merged